name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.17.x"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: install google-cloud-sdk
        run: |
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-pubsub-emulator -y
      - name: "go vet"
        run: |
          go vet ./...
      - name: "go test"
        run: |
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v2
